---
- name: Install java
  apt:
    name: openjdk-11-jre

- name: Check if syncrify is installed
  stat:
    path: /opt/Syncrify
  register: syncrify_folder

- name: Download syncrify server
  get_url:
    url: http://www2.synametrics.com/files/Syncrify/SyncrifyLinux64.tar
    dest: /tmp/syncrify-server.tar
  when: not syncrify_folder.stat.exists

- name: Create extraction dir
  file:
    path: /tmp/syncrify
    state: directory
    recurse: yes
  when: not syncrify_folder.stat.exists

- name: Unarchive syncrify files
  unarchive:
    src: /tmp/syncrify-server.tar
    dest: /tmp/syncrify
    remote_src: yes
  when: not syncrify_folder.stat.exists

- name: Set executable for Install.sh
  file:
    path: /tmp/syncrify/Install.sh
    owner: root
    group: root
    mode: '0700'
  when: not syncrify_folder.stat.exists

- name: Run install script
  command: sh Install.sh
  args:
    chdir: /tmp/syncrify/
  when: not syncrify_folder.stat.exists

- name: Place AppConfig.xml
  template:
    src: AppConfig.xml.j2
    dest: /opt/Syncrify/config/AppConfig.xml

- name: Ensure group "{{ syncrify_server_group }}" exists
  group:
    name: "{{ syncrify_server_group }}"

- name: Add syncrify user
  user:
    name: "{{ syncrify_server_user }}"

- name: Set owner and group for files
  file:
    path: /opt/Syncrify
    owner: "{{ syncrify_server_user }}"
    group: "{{ syncrify_server_group }}"
    recurse: yes

- name: Add syncrify systemd service
  template:
    src: syncrify.service.j2
    dest: /etc/systemd/system/syncrify.service
    owner: root
    group: root
    mode: 0644
  register: unit

- name: Enable and start
  systemd:
    name: syncrify.service
    state: started
    enabled: true
    daemon_reload: "{{ unit.changed }}"
